// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XREORDER_RESIZE_H
#define XREORDER_RESIZE_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xreorder_resize_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XReorder_resize_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XReorder_resize;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XReorder_resize_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XReorder_resize_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XReorder_resize_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XReorder_resize_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XReorder_resize_Initialize(XReorder_resize *InstancePtr, u16 DeviceId);
XReorder_resize_Config* XReorder_resize_LookupConfig(u16 DeviceId);
int XReorder_resize_CfgInitialize(XReorder_resize *InstancePtr, XReorder_resize_Config *ConfigPtr);
#else
int XReorder_resize_Initialize(XReorder_resize *InstancePtr, const char* InstanceName);
int XReorder_resize_Release(XReorder_resize *InstancePtr);
#endif


void XReorder_resize_Set_dst_rows(XReorder_resize *InstancePtr, u32 Data);
u32 XReorder_resize_Get_dst_rows(XReorder_resize *InstancePtr);
void XReorder_resize_Set_dst_cols(XReorder_resize *InstancePtr, u32 Data);
u32 XReorder_resize_Get_dst_cols(XReorder_resize *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
