// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Block_Mat_exit88_pro (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        rows,
        cols,
        bound_y_min,
        bound_y_min_ap_vld,
        bound_y_max,
        bound_y_max_ap_vld,
        img_1_rows_V_out_din,
        img_1_rows_V_out_full_n,
        img_1_rows_V_out_write,
        img_1_cols_V_out_din,
        img_1_cols_V_out_full_n,
        img_1_cols_V_out_write,
        img_2_rows_V_out_din,
        img_2_rows_V_out_full_n,
        img_2_rows_V_out_write,
        img_2_cols_V_out_din,
        img_2_cols_V_out_full_n,
        img_2_cols_V_out_write,
        bound_y_min_out_din,
        bound_y_min_out_full_n,
        bound_y_min_out_write,
        bound_y_max_out_din,
        bound_y_max_out_full_n,
        bound_y_max_out_write,
        ap_return_0,
        ap_return_1
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [31:0] rows;
input  [31:0] cols;
input  [15:0] bound_y_min;
input   bound_y_min_ap_vld;
input  [15:0] bound_y_max;
input   bound_y_max_ap_vld;
output  [31:0] img_1_rows_V_out_din;
input   img_1_rows_V_out_full_n;
output   img_1_rows_V_out_write;
output  [31:0] img_1_cols_V_out_din;
input   img_1_cols_V_out_full_n;
output   img_1_cols_V_out_write;
output  [31:0] img_2_rows_V_out_din;
input   img_2_rows_V_out_full_n;
output   img_2_rows_V_out_write;
output  [31:0] img_2_cols_V_out_din;
input   img_2_cols_V_out_full_n;
output   img_2_cols_V_out_write;
output  [15:0] bound_y_min_out_din;
input   bound_y_min_out_full_n;
output   bound_y_min_out_write;
output  [15:0] bound_y_max_out_din;
input   bound_y_max_out_full_n;
output   bound_y_max_out_write;
output  [31:0] ap_return_0;
output  [31:0] ap_return_1;

reg ap_done;
reg ap_idle;
reg start_write;
reg img_1_rows_V_out_write;
reg img_1_cols_V_out_write;
reg img_2_rows_V_out_write;
reg img_2_cols_V_out_write;
reg bound_y_min_out_write;
reg bound_y_max_out_write;
reg[31:0] ap_return_0;
reg[31:0] ap_return_1;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    bound_y_min_blk_n;
reg    bound_y_max_blk_n;
reg    img_1_rows_V_out_blk_n;
reg    img_1_cols_V_out_blk_n;
reg    img_2_rows_V_out_blk_n;
reg    img_2_cols_V_out_blk_n;
reg    bound_y_min_out_blk_n;
reg    bound_y_max_out_blk_n;
reg    ap_block_state1;
reg   [31:0] ap_return_0_preg;
reg   [31:0] ap_return_1_preg;
reg   [0:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_return_0_preg = 32'd0;
#0 ap_return_1_preg = 32'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((real_start == 1'b0) | (bound_y_max_out_full_n == 1'b0) | (bound_y_min_out_full_n == 1'b0) | (img_2_cols_V_out_full_n == 1'b0) | (img_2_rows_V_out_full_n == 1'b0) | (img_1_cols_V_out_full_n == 1'b0) | (img_1_rows_V_out_full_n == 1'b0) | (bound_y_max_ap_vld == 1'b0) | (bound_y_min_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_0_preg <= 32'd0;
    end else begin
        if ((~((real_start == 1'b0) | (bound_y_max_out_full_n == 1'b0) | (bound_y_min_out_full_n == 1'b0) | (img_2_cols_V_out_full_n == 1'b0) | (img_2_rows_V_out_full_n == 1'b0) | (img_1_cols_V_out_full_n == 1'b0) | (img_1_rows_V_out_full_n == 1'b0) | (bound_y_max_ap_vld == 1'b0) | (bound_y_min_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_0_preg <= rows;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_1_preg <= 32'd0;
    end else begin
        if ((~((real_start == 1'b0) | (bound_y_max_out_full_n == 1'b0) | (bound_y_min_out_full_n == 1'b0) | (img_2_cols_V_out_full_n == 1'b0) | (img_2_rows_V_out_full_n == 1'b0) | (img_1_cols_V_out_full_n == 1'b0) | (img_1_rows_V_out_full_n == 1'b0) | (bound_y_max_ap_vld == 1'b0) | (bound_y_min_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_1_preg <= cols;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (bound_y_max_out_full_n == 1'b0) | (bound_y_min_out_full_n == 1'b0) | (img_2_cols_V_out_full_n == 1'b0) | (img_2_rows_V_out_full_n == 1'b0) | (img_1_cols_V_out_full_n == 1'b0) | (img_1_rows_V_out_full_n == 1'b0) | (bound_y_max_ap_vld == 1'b0) | (bound_y_min_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (bound_y_max_out_full_n == 1'b0) | (bound_y_min_out_full_n == 1'b0) | (img_2_cols_V_out_full_n == 1'b0) | (img_2_rows_V_out_full_n == 1'b0) | (img_1_cols_V_out_full_n == 1'b0) | (img_1_rows_V_out_full_n == 1'b0) | (bound_y_max_ap_vld == 1'b0) | (bound_y_min_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_0 = rows;
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (bound_y_max_out_full_n == 1'b0) | (bound_y_min_out_full_n == 1'b0) | (img_2_cols_V_out_full_n == 1'b0) | (img_2_rows_V_out_full_n == 1'b0) | (img_1_cols_V_out_full_n == 1'b0) | (img_1_rows_V_out_full_n == 1'b0) | (bound_y_max_ap_vld == 1'b0) | (bound_y_min_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_1 = cols;
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        bound_y_max_blk_n = bound_y_max_ap_vld;
    end else begin
        bound_y_max_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        bound_y_max_out_blk_n = bound_y_max_out_full_n;
    end else begin
        bound_y_max_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (bound_y_max_out_full_n == 1'b0) | (bound_y_min_out_full_n == 1'b0) | (img_2_cols_V_out_full_n == 1'b0) | (img_2_rows_V_out_full_n == 1'b0) | (img_1_cols_V_out_full_n == 1'b0) | (img_1_rows_V_out_full_n == 1'b0) | (bound_y_max_ap_vld == 1'b0) | (bound_y_min_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        bound_y_max_out_write = 1'b1;
    end else begin
        bound_y_max_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        bound_y_min_blk_n = bound_y_min_ap_vld;
    end else begin
        bound_y_min_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        bound_y_min_out_blk_n = bound_y_min_out_full_n;
    end else begin
        bound_y_min_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (bound_y_max_out_full_n == 1'b0) | (bound_y_min_out_full_n == 1'b0) | (img_2_cols_V_out_full_n == 1'b0) | (img_2_rows_V_out_full_n == 1'b0) | (img_1_cols_V_out_full_n == 1'b0) | (img_1_rows_V_out_full_n == 1'b0) | (bound_y_max_ap_vld == 1'b0) | (bound_y_min_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        bound_y_min_out_write = 1'b1;
    end else begin
        bound_y_min_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        img_1_cols_V_out_blk_n = img_1_cols_V_out_full_n;
    end else begin
        img_1_cols_V_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (bound_y_max_out_full_n == 1'b0) | (bound_y_min_out_full_n == 1'b0) | (img_2_cols_V_out_full_n == 1'b0) | (img_2_rows_V_out_full_n == 1'b0) | (img_1_cols_V_out_full_n == 1'b0) | (img_1_rows_V_out_full_n == 1'b0) | (bound_y_max_ap_vld == 1'b0) | (bound_y_min_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        img_1_cols_V_out_write = 1'b1;
    end else begin
        img_1_cols_V_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        img_1_rows_V_out_blk_n = img_1_rows_V_out_full_n;
    end else begin
        img_1_rows_V_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (bound_y_max_out_full_n == 1'b0) | (bound_y_min_out_full_n == 1'b0) | (img_2_cols_V_out_full_n == 1'b0) | (img_2_rows_V_out_full_n == 1'b0) | (img_1_cols_V_out_full_n == 1'b0) | (img_1_rows_V_out_full_n == 1'b0) | (bound_y_max_ap_vld == 1'b0) | (bound_y_min_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        img_1_rows_V_out_write = 1'b1;
    end else begin
        img_1_rows_V_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        img_2_cols_V_out_blk_n = img_2_cols_V_out_full_n;
    end else begin
        img_2_cols_V_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (bound_y_max_out_full_n == 1'b0) | (bound_y_min_out_full_n == 1'b0) | (img_2_cols_V_out_full_n == 1'b0) | (img_2_rows_V_out_full_n == 1'b0) | (img_1_cols_V_out_full_n == 1'b0) | (img_1_rows_V_out_full_n == 1'b0) | (bound_y_max_ap_vld == 1'b0) | (bound_y_min_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        img_2_cols_V_out_write = 1'b1;
    end else begin
        img_2_cols_V_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        img_2_rows_V_out_blk_n = img_2_rows_V_out_full_n;
    end else begin
        img_2_rows_V_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (bound_y_max_out_full_n == 1'b0) | (bound_y_min_out_full_n == 1'b0) | (img_2_cols_V_out_full_n == 1'b0) | (img_2_rows_V_out_full_n == 1'b0) | (img_1_cols_V_out_full_n == 1'b0) | (img_1_rows_V_out_full_n == 1'b0) | (bound_y_max_ap_vld == 1'b0) | (bound_y_min_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        img_2_rows_V_out_write = 1'b1;
    end else begin
        img_2_rows_V_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (bound_y_max_out_full_n == 1'b0) | (bound_y_min_out_full_n == 1'b0) | (img_2_cols_V_out_full_n == 1'b0) | (img_2_rows_V_out_full_n == 1'b0) | (img_1_cols_V_out_full_n == 1'b0) | (img_1_rows_V_out_full_n == 1'b0) | (bound_y_max_ap_vld == 1'b0) | (bound_y_min_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (bound_y_max_out_full_n == 1'b0) | (bound_y_min_out_full_n == 1'b0) | (img_2_cols_V_out_full_n == 1'b0) | (img_2_rows_V_out_full_n == 1'b0) | (img_1_cols_V_out_full_n == 1'b0) | (img_1_rows_V_out_full_n == 1'b0) | (bound_y_max_ap_vld == 1'b0) | (bound_y_min_ap_vld == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign bound_y_max_out_din = bound_y_max;

assign bound_y_min_out_din = bound_y_min;

assign img_1_cols_V_out_din = cols;

assign img_1_rows_V_out_din = rows;

assign img_2_cols_V_out_din = cols;

assign img_2_rows_V_out_din = rows;

assign start_out = real_start;

endmodule //Block_Mat_exit88_pro
