// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xcontrast_hls_rom.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XContrast_hls_rom_CfgInitialize(XContrast_hls_rom *InstancePtr, XContrast_hls_rom_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XContrast_hls_rom_Start(XContrast_hls_rom *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XContrast_hls_rom_ReadReg(InstancePtr->Axilites_BaseAddress, XCONTRAST_HLS_ROM_AXILITES_ADDR_AP_CTRL) & 0x80;
    XContrast_hls_rom_WriteReg(InstancePtr->Axilites_BaseAddress, XCONTRAST_HLS_ROM_AXILITES_ADDR_AP_CTRL, Data | 0x01);
}

u32 XContrast_hls_rom_IsDone(XContrast_hls_rom *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XContrast_hls_rom_ReadReg(InstancePtr->Axilites_BaseAddress, XCONTRAST_HLS_ROM_AXILITES_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XContrast_hls_rom_IsIdle(XContrast_hls_rom *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XContrast_hls_rom_ReadReg(InstancePtr->Axilites_BaseAddress, XCONTRAST_HLS_ROM_AXILITES_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XContrast_hls_rom_IsReady(XContrast_hls_rom *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XContrast_hls_rom_ReadReg(InstancePtr->Axilites_BaseAddress, XCONTRAST_HLS_ROM_AXILITES_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XContrast_hls_rom_EnableAutoRestart(XContrast_hls_rom *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XContrast_hls_rom_WriteReg(InstancePtr->Axilites_BaseAddress, XCONTRAST_HLS_ROM_AXILITES_ADDR_AP_CTRL, 0x80);
}

void XContrast_hls_rom_DisableAutoRestart(XContrast_hls_rom *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XContrast_hls_rom_WriteReg(InstancePtr->Axilites_BaseAddress, XCONTRAST_HLS_ROM_AXILITES_ADDR_AP_CTRL, 0);
}

void XContrast_hls_rom_InterruptGlobalEnable(XContrast_hls_rom *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XContrast_hls_rom_WriteReg(InstancePtr->Axilites_BaseAddress, XCONTRAST_HLS_ROM_AXILITES_ADDR_GIE, 1);
}

void XContrast_hls_rom_InterruptGlobalDisable(XContrast_hls_rom *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XContrast_hls_rom_WriteReg(InstancePtr->Axilites_BaseAddress, XCONTRAST_HLS_ROM_AXILITES_ADDR_GIE, 0);
}

void XContrast_hls_rom_InterruptEnable(XContrast_hls_rom *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XContrast_hls_rom_ReadReg(InstancePtr->Axilites_BaseAddress, XCONTRAST_HLS_ROM_AXILITES_ADDR_IER);
    XContrast_hls_rom_WriteReg(InstancePtr->Axilites_BaseAddress, XCONTRAST_HLS_ROM_AXILITES_ADDR_IER, Register | Mask);
}

void XContrast_hls_rom_InterruptDisable(XContrast_hls_rom *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XContrast_hls_rom_ReadReg(InstancePtr->Axilites_BaseAddress, XCONTRAST_HLS_ROM_AXILITES_ADDR_IER);
    XContrast_hls_rom_WriteReg(InstancePtr->Axilites_BaseAddress, XCONTRAST_HLS_ROM_AXILITES_ADDR_IER, Register & (~Mask));
}

void XContrast_hls_rom_InterruptClear(XContrast_hls_rom *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XContrast_hls_rom_WriteReg(InstancePtr->Axilites_BaseAddress, XCONTRAST_HLS_ROM_AXILITES_ADDR_ISR, Mask);
}

u32 XContrast_hls_rom_InterruptGetEnabled(XContrast_hls_rom *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XContrast_hls_rom_ReadReg(InstancePtr->Axilites_BaseAddress, XCONTRAST_HLS_ROM_AXILITES_ADDR_IER);
}

u32 XContrast_hls_rom_InterruptGetStatus(XContrast_hls_rom *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XContrast_hls_rom_ReadReg(InstancePtr->Axilites_BaseAddress, XCONTRAST_HLS_ROM_AXILITES_ADDR_ISR);
}

