// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xdraw_line_hls.h"

extern XDraw_line_hls_Config XDraw_line_hls_ConfigTable[];

XDraw_line_hls_Config *XDraw_line_hls_LookupConfig(u16 DeviceId) {
	XDraw_line_hls_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XDRAW_LINE_HLS_NUM_INSTANCES; Index++) {
		if (XDraw_line_hls_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XDraw_line_hls_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XDraw_line_hls_Initialize(XDraw_line_hls *InstancePtr, u16 DeviceId) {
	XDraw_line_hls_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XDraw_line_hls_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XDraw_line_hls_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

