// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// AXILiteS
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : Data signal of rows
//        bit 31~0 - rows[31:0] (Read/Write)
// 0x14 : reserved
// 0x18 : Data signal of cols
//        bit 31~0 - cols[31:0] (Read/Write)
// 0x1c : reserved
// 0x20 : Data signal of box_num
//        bit 7~0 - box_num[7:0] (Read/Write)
//        others  - reserved
// 0x24 : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XDRAW_LINE_HLS_AXILITES_ADDR_AP_CTRL      0x00
#define XDRAW_LINE_HLS_AXILITES_ADDR_GIE          0x04
#define XDRAW_LINE_HLS_AXILITES_ADDR_IER          0x08
#define XDRAW_LINE_HLS_AXILITES_ADDR_ISR          0x0c
#define XDRAW_LINE_HLS_AXILITES_ADDR_ROWS_DATA    0x10
#define XDRAW_LINE_HLS_AXILITES_BITS_ROWS_DATA    32
#define XDRAW_LINE_HLS_AXILITES_ADDR_COLS_DATA    0x18
#define XDRAW_LINE_HLS_AXILITES_BITS_COLS_DATA    32
#define XDRAW_LINE_HLS_AXILITES_ADDR_BOX_NUM_DATA 0x20
#define XDRAW_LINE_HLS_AXILITES_BITS_BOX_NUM_DATA 8

