// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xmask.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XMask_CfgInitialize(XMask *InstancePtr, XMask_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XMask_Start(XMask *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMask_ReadReg(InstancePtr->Axilites_BaseAddress, XMASK_AXILITES_ADDR_AP_CTRL) & 0x80;
    XMask_WriteReg(InstancePtr->Axilites_BaseAddress, XMASK_AXILITES_ADDR_AP_CTRL, Data | 0x01);
}

u32 XMask_IsDone(XMask *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMask_ReadReg(InstancePtr->Axilites_BaseAddress, XMASK_AXILITES_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XMask_IsIdle(XMask *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMask_ReadReg(InstancePtr->Axilites_BaseAddress, XMASK_AXILITES_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XMask_IsReady(XMask *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMask_ReadReg(InstancePtr->Axilites_BaseAddress, XMASK_AXILITES_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XMask_EnableAutoRestart(XMask *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMask_WriteReg(InstancePtr->Axilites_BaseAddress, XMASK_AXILITES_ADDR_AP_CTRL, 0x80);
}

void XMask_DisableAutoRestart(XMask *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMask_WriteReg(InstancePtr->Axilites_BaseAddress, XMASK_AXILITES_ADDR_AP_CTRL, 0);
}

void XMask_Set_rows(XMask *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMask_WriteReg(InstancePtr->Axilites_BaseAddress, XMASK_AXILITES_ADDR_ROWS_DATA, Data);
}

u32 XMask_Get_rows(XMask *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMask_ReadReg(InstancePtr->Axilites_BaseAddress, XMASK_AXILITES_ADDR_ROWS_DATA);
    return Data;
}

void XMask_Set_cols(XMask *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMask_WriteReg(InstancePtr->Axilites_BaseAddress, XMASK_AXILITES_ADDR_COLS_DATA, Data);
}

u32 XMask_Get_cols(XMask *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMask_ReadReg(InstancePtr->Axilites_BaseAddress, XMASK_AXILITES_ADDR_COLS_DATA);
    return Data;
}

void XMask_Set_shrink_x_min(XMask *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMask_WriteReg(InstancePtr->Axilites_BaseAddress, XMASK_AXILITES_ADDR_SHRINK_X_MIN_DATA, Data);
}

u32 XMask_Get_shrink_x_min(XMask *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMask_ReadReg(InstancePtr->Axilites_BaseAddress, XMASK_AXILITES_ADDR_SHRINK_X_MIN_DATA);
    return Data;
}

void XMask_Set_shrink_x_max(XMask *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMask_WriteReg(InstancePtr->Axilites_BaseAddress, XMASK_AXILITES_ADDR_SHRINK_X_MAX_DATA, Data);
}

u32 XMask_Get_shrink_x_max(XMask *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMask_ReadReg(InstancePtr->Axilites_BaseAddress, XMASK_AXILITES_ADDR_SHRINK_X_MAX_DATA);
    return Data;
}

void XMask_Set_shrink_y_min(XMask *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMask_WriteReg(InstancePtr->Axilites_BaseAddress, XMASK_AXILITES_ADDR_SHRINK_Y_MIN_DATA, Data);
}

u32 XMask_Get_shrink_y_min(XMask *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMask_ReadReg(InstancePtr->Axilites_BaseAddress, XMASK_AXILITES_ADDR_SHRINK_Y_MIN_DATA);
    return Data;
}

void XMask_Set_shrink_y_max(XMask *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMask_WriteReg(InstancePtr->Axilites_BaseAddress, XMASK_AXILITES_ADDR_SHRINK_Y_MAX_DATA, Data);
}

u32 XMask_Get_shrink_y_max(XMask *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMask_ReadReg(InstancePtr->Axilites_BaseAddress, XMASK_AXILITES_ADDR_SHRINK_Y_MAX_DATA);
    return Data;
}

void XMask_InterruptGlobalEnable(XMask *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMask_WriteReg(InstancePtr->Axilites_BaseAddress, XMASK_AXILITES_ADDR_GIE, 1);
}

void XMask_InterruptGlobalDisable(XMask *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMask_WriteReg(InstancePtr->Axilites_BaseAddress, XMASK_AXILITES_ADDR_GIE, 0);
}

void XMask_InterruptEnable(XMask *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMask_ReadReg(InstancePtr->Axilites_BaseAddress, XMASK_AXILITES_ADDR_IER);
    XMask_WriteReg(InstancePtr->Axilites_BaseAddress, XMASK_AXILITES_ADDR_IER, Register | Mask);
}

void XMask_InterruptDisable(XMask *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMask_ReadReg(InstancePtr->Axilites_BaseAddress, XMASK_AXILITES_ADDR_IER);
    XMask_WriteReg(InstancePtr->Axilites_BaseAddress, XMASK_AXILITES_ADDR_IER, Register & (~Mask));
}

void XMask_InterruptClear(XMask *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMask_WriteReg(InstancePtr->Axilites_BaseAddress, XMASK_AXILITES_ADDR_ISR, Mask);
}

u32 XMask_InterruptGetEnabled(XMask *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMask_ReadReg(InstancePtr->Axilites_BaseAddress, XMASK_AXILITES_ADDR_IER);
}

u32 XMask_InterruptGetStatus(XMask *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMask_ReadReg(InstancePtr->Axilites_BaseAddress, XMASK_AXILITES_ADDR_ISR);
}

